name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t simple-app .

    - name: Run the Application
      run: docker run simple-app